# **Tutorial 1 Python: Data Types and Data Structures**




##Basic Variable Types

In [ ]:
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [ ]:
my_string1 = 'Hello to'
my_string2 = "everyone reading this"
print(my_string1 + ' ' + my_string2)

Hello to everyone reading this


In [ ]:
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [ ]:
my_int = 57
print(my_int)
print(type(my_int))

57
<class 'int'>


In [ ]:
my_string = "100"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [ ]:
my_float = 1.0
print(type(my_float))
my_int = 1
print(type(my_int))

<class 'float'>
<class 'int'>


In [ ]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [ ]:
my_bool = False
print(my_bool)
print(type(my_bool))

False
<class 'bool'>


In [ ]:
my_bool = True
print(my_bool)
print(type(my_bool))

True
<class 'bool'>


## Basic Math Operations

In [ ]:
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [ ]:
print("Addition ", 13+5)
print("Subtraction ", 4-7)
print("Multiplication ", 13*6)
print("Division", 15/3)
print("exponent", 4**2)

Addition  18
Subtraction  -3
Multiplication  78
Division 5.0
exponent 16


##Data Collections

In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [ ]:
my_list = [3278, 'Tutorial', 'Algorithms', 5, 8, 'Hi']
print(my_list)

[3278, 'Tutorial', 'Algorithms', 5, 8, 'Hi']


In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

5
Quant
3


In [ ]:
my_list = [3278, 'Tutorial', 'Algorithms',5 ,8, 'Hi']
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

6
3278
Hi


In [ ]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [ ]:
my_list = [3278, 'Tutorial', 'Algorithms',5 ,8, 'Hi']
my_list[3] = 'task'
print(my_list)

[3278, 'Tutorial', 'Algorithms', 'task', 8, 'Hi']


In [ ]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [ ]:
my_list = [3278, 'Tutorial', 'Algorithms',5 ,8, 'Hi']
print(my_list[2:5])

['Algorithms', 5, 8]


In [ ]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:])

['Connect', 1, 2, 3]


In [ ]:
my_list = [3278, 'Tutorial', 'Algorithms',5 ,8, 'Hi']
print(my_list[4:])

[8, 'Hi']


In [ ]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[:3])

['Quant', 'Connect', 1]


In [ ]:
my_list = [3278, 'Tutorial', 'Algorithms',5 ,8, 'Hi']
print(my_list[:2])

[3278, 'Tutorial']


In [ ]:
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)
my_list.remove('Hello')
print(my_list)

['Hello', 'Quant', 'Hello']
['Quant', 'Hello']


In [ ]:
my_list = ['Hi', 'October']
my_list.append('Music')
print(my_list)
my_list.remove('October')
print(my_list)

['Hi', 'October', 'Music']
['Hi', 'Music']


In [ ]:
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [ ]:
my_tuple=('Gracias', 'por', 'el', 5)
print(my_tuple[2:])

('el', 5)


In [ ]:
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'IBM', 'AAPL', 'FB', 'GOOG', 'F'}


In [ ]:
stock_list = ['Universidad','Nacional','De','Colombia', 'De', 'Colombia']
stock_set = set(stock_list)
print(stock_set)

{'Nacional', 'Colombia', 'De', 'Universidad'}


In [ ]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
print(my_dic['GOOG'])

Alphabet


In [ ]:
my_dic = {'TWT': 'Twitter', 'ING': 'Instagram', 'DSC': 'Discord', 'RDT':'Reddit'}
print(my_dic['RDT'])

Reddit


In [ ]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [ ]:
my_dic = {'TWT': 'Twitter', 'ING': 'Instagram', 'DSC': 'Discord', 'RDT':'Reddit'}
my_dic['RDT'] = 'Raid'
print(my_dic['RDT'])

Raid


In [ ]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
print(my_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


In [ ]:
my_dic = {'TWT': 'Twitter', 'ING': 'Instagram', 'DSC': 'Discord', 'RDT':'Reddit'}
print(my_dic.keys())

dict_keys(['TWT', 'ING', 'DSC', 'RDT'])


##Common String Operations

In [ ]:
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [ ]:
my_str = 'Thanks for reading this'
print(my_str[11:])

reading this


In [ ]:
print("Counting the number of e's in this sentence".count('e'))
print('The first time e appears in this sentence'.find('e'))
print('all the a in this sentence now becomes e'.replace('a','e'))

6
2
ell the e in this sentence now becomes e


In [ ]:
print("Se va a contar la cantidad de a´s en esta frase".count('a'))
print('Buscando la primera r dentro de esta frase'.find('r'))
print('Todas las o de esta frase se volverán a'.replace('o','a'))

9
13
Tadas las a de esta frase se valverán a


In [ ]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[0]
print(hour)

2016-04-01 09:43:00
09


In [ ]:
nombre='Zambrano,David'
splited_list=nombre.split(',')
apellido=splited_list[0]
nombre=splited_list[1]
print('Nombre:', nombre)
print('Apellido:', apellido)

Nombre: David
Apellido: Zambrano


In [ ]:
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [ ]:
data='Cantidad de estudiantes: {}, Cantidad de aprobados: {}'.format(35, 27)
print(data)

Cantidad de estudiantes: 35, Cantidad de aprobados: 27


In [ ]:
print('pi is %f' % 3.14)
print('%s to %s' % ('Welcome', 'QuantConnect'))

pi is 3.140000
Welcome to QuantConnect


In [ ]:
print('After %i hours i finished the %i tutorial' % (2, 1))

After 2 hours i finished the 1 tutorial


#**Tutorial 2 Python: Logical Operations and Loop**

##Logical Operations

In [ ]:
print(1 == 0)    # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)    # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [ ]:
print(20 == 3)    # 20 equals 3
print(7 == 7)    # 7 equals 7
print(21 != 21)    # 21 is not equal to 21
print(7 >= 13)    # 7 is greater than or equal to 13
print(34 >= 2)    # 34 is greater than or equal to 2

False
True
False
False
True


In [ ]:
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2)
print(2 > 1 or  3 < 2)
print(2 < 1 and 3 < 2)

True
False
True
False


In [ ]:
print(12 > 5 and  24> 13)
print(31 > 33 and 7 < 34)
print(13 > 9 or  8 < 34)
print(5 < 1 or 12 < 6)

True
False
True
False


In [ ]:
print((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

False
True


In [ ]:
print( not ((27<=12 and 56==13) and (5<13 or 17> 12)) and ((12==12 and 13 != 22) or not (32 < 44 or 67 != 13)))

True


##If Statement

In [ ]:
i = 0
if i == 0: 
  print('i == 0 is True')

i == 0 is True


In [ ]:
j = 23
if j < 50:
  print('j ==', j, 'is True')

j == 23 is True


In [ ]:
p = 1 > 0
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

q is false


In [ ]:
a = 17
b = 34
if a < b:
  print('b is greater than a')
elif a > b:
  print('a is greater than b')
else:
  print('a is equal to b')

b is greater than a


##Loop Structure

In [ ]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [ ]:
i=0
while i != 4:
  print('Mensaje', i)
  i +=1

Mensaje 0
Mensaje 1
Mensaje 2
Mensaje 3


In [ ]:
for x in [1,2,3,4,5]: 
  print(x)

1
2
3
4
5


In [ ]:
for i in range(5):
  print(i, 'loops')

0 loops
1 loops
2 loops
3 loops
4 loops


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [ ]:
numbers=[2, 4, 67, 13, 97, 36, 89, 34 ,3, 78, 90, 45]
empty_list=[]
for i in numbers:
  if i <= 50:
    empty_list.append(i)
print(empty_list)

[2, 4, 13, 36, 34, 3, 45]


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print(stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [ ]:
numbers=[2, 4, 67, 13, 97, 36, 89, 34 ,3, 78, 90, 45]
for i in numbers:
  if i >= 50:
    break
  print(i)

2
4


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print(stock)

AAPL
GOOG
IBM
F
V
G
GE


In [ ]:
numbers=[2, 4, 67, 13, 97, 36, 89, 34 ,3, 78, 90, 45]
for i in numbers:
  if i >= 50:
    continue
  print(i)

2
4
13
36
34
3
45


##List Comprehension

In [ ]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
result = []
for i in [4,15,20,2,10]:
    result.append((i*13)+7)
print(result)

[59, 202, 267, 33, 137]


In [ ]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
op_list=[4,15,20,2,10]
result = [(i*13)+7 for i in op_list]
print(result)

[59, 202, 267, 33, 137]


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [ ]:
numbers=[2, 4, 67, 13, 97, 36, 89, 34 ,3, 78, 90, 45]
empty_list=[i for i in numbers if i <= 50]
print(empty_list)

[2, 4, 13, 36, 34, 3, 45]


In [ ]:
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [ ]:
print([(x,y) for x in [1,2,3,4] for y in [1,2,3,4] if x!=y])

[(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4), (3, 1), (3, 2), (3, 4), (4, 1), (4, 2), (4, 3)]


#**Tutorial 3 Functions and Objective-Oriented Programming**

##Functions

In [ ]:
def product(x,y):
    return x*y
print(product(2,3))
print(product(5,10))

6
50


In [5]:
def operation(x,y):
  return int(2*(x+13/y))
print(operation(10,12))
print(operation(2,5))

22
9


In [ ]:
def say_hi():
    print('Welcome to QuantConnect')
say_hi()

Welcome to QuantConnect


In [8]:
def hello():
  print('Hello world')
hello()

Hello world


##Built-in Function

In [13]:
print([x for x in range(10)])
print([x for x in range(1, 11)])
print([x for x in range(1, 11, 2)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9]


In [14]:
print([x for x in range(0,12,3)])

[0, 3, 6, 9]


In [15]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [19]:
numbers=[1,2,6,87,13,56,0,24]
print('The number of numbers is', len(numbers))
numbers.sort()
for k in range(len(numbers)):
  print(numbers[k])

The number of numbers is 8
0
1
2
6
13
24
56
87


In [20]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [22]:
def mult(x):
  return x*2
numbers=[1,2,6,87,13,56,0,24]
print(list(map(mult,numbers)))

[2, 4, 12, 174, 26, 112, 0, 48]


In [24]:
list(map(lambda x: x**2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [25]:
list(map(lambda x: int((x**3)/2), range(8)))

[0, 0, 4, 13, 32, 62, 108, 171]

In [27]:
list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1]))

[6, 6, 6, 6, 6]

In [28]:
list(map(lambda x, y: x*y, [1,6,12,13,7], [25,34,78,12,14]))

[25, 204, 936, 156, 98]

In [29]:
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [30]:
sorted([1,2,6,87,13,56,0,24])

[0, 1, 2, 6, 13, 24, 56, 87]

In [33]:
price_list = [('AAPL', 144.09),('GOOGL', 911.71),('MSFT', 69),('FB', 150),('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [38]:
price_list = [1,2,6,87,13,56,24]
sorted(price_list, key = lambda x: x < 50)

[87, 56, 1, 2, 6, 13, 24]

In [39]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [40]:
price_list = [1,2,6,87,13,56,24]
sorted(price_list, key = lambda x: x < 50, reverse=True)

[1, 2, 6, 13, 24, 87, 56]

In [41]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [42]:
price_list = [1,2,6,87,13,56,24]
price_list.sort(key = lambda x: x < 50)
print(price_list)

[87, 56, 1, 2, 6, 13, 24]


##Object-Oriented Programming

In [45]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)
print(apple.ticker)
google.print_return()
google.update(912.8,913.4)
google.print_return()

AAPL
0.014465338822744034
0.0006573181419806673


In [70]:
class Person:
  def __init__(self,name,lastname,age,phone):
    self.name = name
    self.lastname = lastname
    self.age = age
    self.phone = phone
  def complete(self):
    print(self.name, self.lastname)
  def updatePhone(self, phone):
    self.phone = phone
person1 = Person('Pepe', 'Perez', 24, 1231241)
person2 = Person('Juan', 'Rodriguez', 21, 12324324)
print(person2.age)
person1.complete()
person1.updatePhone(689575746)
person2.complete()

21
Pepe Perez
Juan Rodriguez


In [46]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [71]:
person1.degree = 'college'
person1.degree

'college'

In [47]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [72]:
dir(person1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'complete',
 'degree',
 'lastname',
 'name',
 'phone',
 'updatePhone']

In [56]:
class Child(Stock):
    def __init__(self, name):
        self.name = name
aa = Child('AA')
print(aa.name)
aa.update(100, 102)
print(aa.open)
print(aa.close)
aa.print_return()

AA
100
102
0.020000000000000018


In [74]:
class Newest(Person):
  def __init__(self,name):
    self.name = name
person3 = Newest('Jorge')
print(person3.name)
person3.updatePhone(4372343)
print(person3.phone)

Jorge
4372343


#**Tutorial 4 NumPy and Basic Pandas**

##NumPy

In [75]:
import numpy as np

In [76]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [84]:
numbers_list = [56.2, 43.6, 23.4, 12.4, 76.7, 23.9, 87.4, 23.3, 45.2]
numbers_array = np.array(numbers_list)
print(numbers_array, type(numbers_array))

[56.2 43.6 23.4 12.4 76.7 23.9 87.4 23.3 45.2] <class 'numpy.ndarray'>


In [77]:
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [86]:
ex_ar = np.array([[42,27], [13,12]])
print(ex_ar, type(ex_ar))

[[42 27]
 [13 12]] <class 'numpy.ndarray'>


In [78]:
print(Ar.shape)

(2, 2)


In [87]:
print(ex_ar.shape)

(2, 2)


In [89]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [90]:
print(ex_ar[0])
print(ex_ar[1])

[42 27]
[13 12]


In [93]:
print('First column:', Ar[:,0])
print('Second column:', Ar[:,1])

First column: [1 2]
Second column: [3 4]


In [94]:
print('First column:', ex_ar[:,0])
print('Second column:', ex_ar[:,1])

First column: [42 13]
Second column: [27 12]


In [95]:
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [96]:
np.log(numbers_list)

array([4.02891676, 3.77505715, 3.15273602, 2.51769647, 4.33990171,
       3.17387846, 4.47049528, 3.14845336, 3.81109709])

In [99]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [100]:
print(np.mean(numbers_list))
print(np.std(numbers_list))
print(np.sum(numbers_list))
print(np.max(numbers_list))

43.56666666666667
24.397222064088457
392.1
87.4


##Pandas

In [101]:
import pandas as pd

In [128]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [109]:
numbers_list = [56.2, 43.6, 23.4, 12.4, 76.7, 23.9, 87.4, 23.3, 45.2]
a = pd.Series(numbers_list)
print(a)

0    56.2
1    43.6
2    23.4
3    12.4
4    76.7
5    23.9
6    87.4
7    23.3
8    45.2
dtype: float64


In [129]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [113]:
a = pd.Series(numbers_list, index = ['A', 'B', 'C', 'D', 'F', 'E', 'F', 'G', 'H'])
print(a)

A    56.2
B    43.6
C    23.4
D    12.4
F    76.7
E    23.9
F    87.4
G    23.3
H    45.2
dtype: float64


In [130]:
s.index = [6,5,4,3,2,1]
print(s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [116]:
a.index = [9,8,7,6,5,4,3,2,1]
print(a)

9    56.2
8    43.6
7    23.4
6    12.4
5    76.7
4    23.9
3    87.4
2    23.3
1    45.2
dtype: float64


In [131]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [119]:
print(a[4:])
print(a[:-6])

5    76.7
4    23.9
3    87.4
2    23.3
1    45.2
dtype: float64
9    56.2
8    43.6
7    23.4
dtype: float64


In [132]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [123]:
print(a[7])
a[7] = 0
print(a)

23.4
9    56.2
8    43.6
7     0.0
6    12.4
5    76.7
4    23.9
3    87.4
2    23.3
1    45.2
dtype: float64


In [134]:
s = pd.Series(price, name = 'Apple Prices')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [135]:
a = pd.Series(numbers_list, name = 'Lista de números')
print(a)
print(a.name)

0    56.2
1    43.6
2    23.4
3    12.4
4    76.7
5    23.9
6    87.4
7    23.3
8    45.2
Name: Lista de números, dtype: float64
Lista de números


In [136]:
print(s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [138]:
print(a.describe())

count     9.000000
mean     43.566667
std      25.877162
min      12.400000
25%      23.400000
50%      43.600000
75%      56.200000
max      87.400000
Name: Lista de números, dtype: float64


In [139]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [141]:
time_index_a = pd.date_range('2021-10-01', periods = len(a), freq = 'D')
print(time_index_a)
a.index = time_index_a
print(a)

DatetimeIndex(['2021-10-01', '2021-10-02', '2021-10-03', '2021-10-04',
               '2021-10-05', '2021-10-06', '2021-10-07', '2021-10-08',
               '2021-10-09'],
              dtype='datetime64[ns]', freq='D')
2021-10-01    56.2
2021-10-02    43.6
2021-10-03    23.4
2021-10-04    12.4
2021-10-05    76.7
2021-10-06    23.9
2021-10-07    87.4
2021-10-08    23.3
2021-10-09    45.2
Freq: D, Name: Lista de números, dtype: float64


In [142]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [148]:
a.index = [9,8,7,6,5,4,3,2,1]
print(a)
print(a[1])

9    56.2
8    43.6
7    23.4
6    12.4
5    76.7
4    23.9
3    87.4
2    23.3
1    45.2
Name: Lista de números, dtype: float64
45.2


In [144]:
print(s.iloc[1])

145.83


In [149]:
print(a.iloc[1])

43.6


In [146]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [151]:
a.index = time_index_a
print(a['2021-10-03'])

23.4


In [147]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [152]:
print(a['2021-10-01':'2021-10-05'])

2021-10-01    56.2
2021-10-02    43.6
2021-10-03    23.4
2021-10-04    12.4
2021-10-05    76.7
Freq: D, Name: Lista de números, dtype: float64


In [154]:
print(s[s < np.mean(s)])
print(s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])


2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [164]:
print(a[a > np.mean(a)])
print(a[a <= np.std(a)])

2021-10-01    56.2
2021-10-02    43.6
2021-10-05    76.7
2021-10-07    87.4
2021-10-09    45.2
Name: Lista de números, dtype: float64
2021-10-03    23.4
2021-10-04    12.4
2021-10-06    23.9
2021-10-08    23.3
Name: Lista de números, dtype: float64
